TeamPLOY/Bubble_APP

lib/Pages/join_page.dart
=> 회원가입 페이지 완료

lib/Components/Box/cancel.dart, lib/Components/Button/Alarm.dart, lib/Components/Footer/footer.dart
=> refactor : 수정  및 개선

lib/Components/Box/bubblebox.dart, lib/Components/Box/dropdownbox.dart, lib/Components/Footer/footer.dart, lib/Components/Header/header.dart, lib/Components/Header/main_header.dart, lib/Components/Modal/check_modal.dart, lib/Pages/Terms_Use.dart, lib/Pages/my_page.dart
=> fix : 이미지 경로 수정

lib/theme.dart
=> feat : font 설정 추가

lib/Pages/login_page.dart, lib/theme.dart
로그인 페이지 퍼블리싱 완료
로그인 페이지 퍼블리싱 완료
login_page.dart파일 생성
=> 로그인 페이지 퍼블리싱 완료

lib/Components/Button/bluebutton.dart
=> feat : 컴포넌트 수정

lib/Pages/finish.dart
화면 자동 전환
에약 완료 화면 3초 후 메인 페이지로 이동
=> feat : 3초 후 이동

lib/Models/User.dart, lib/Models/token_models.dart, lib/Pages/login_page.dart, lib/Pages/my_page.dart, lib/Utils/login_post.dart, lib/Utils/logout.dart, lib/Utils/user_get.dart
로그인 api연결 완료
로그인 api연결 완료
로그인 api연결 완료
=> 로그인 api연결 완료

lib/Components/Footer/footer.dart, lib/Components/Header/main_header.dart, lib/Components/Modal/check_modal.dart, lib/Pages/Alarm_page/Alarm_page.dart, lib/Pages/Alarm_page/Notice_page.dart, lib/Pages/Alarm_page/Reservation.dart, lib/Pages/finish.dart, lib/Pages/login_page.dart, lib/Pages/main_page.dart, lib/Pages/my_page.dart, lib/Utils/logout.dart, pubspec.lock
자연스럽게 이동 완료
자연스럽게 이동 완료
자연스럽게 이동 완료
=> 자연스럽게 이동 완료

lib/Components/Box/check_box.dart, lib/Components/Button/reservationButton.dart, lib/Components/Modal/check_modal.dart, lib/Models/reservation_models.dart, lib/Pages/reservationpage.dart, lib/Utils/reservation_get.dart, lib/Utils/reservation_post.dart, pubspec.yaml
=> feat : 예약 API 연결

lib/Components/Box/bubblebox.dart, lib/Components/Box/cancel.dart, lib/Components/Modal/cancel_modal.dart, lib/Pages/Alarm_page/Alarm_page.dart, lib/Pages/Alarm_page/Notice_page.dart, lib/Pages/Alarm_page/Reservation.dart, lib/Pages/Terms_Use.dart, lib/Pages/join_page.dart, lib/Utils/cancel_post.dart, lib/Utils/user_get.dart, lib/theme.dart
예약 목록 api 연결 끝
예약 목록 api 연결 끝
예약 목록 api 연결 끝
=> 예약 목록 api 연결 끝

lib/data/Functions/emailsearch.dart, lib/presentation/pages/deleteUser/delete_finish_page.dart, lib/presentation/pages/login/login_page.dart, lib/presentation/pages/onboarding/onboarding_page.dart, lib/presentation/pages/reservation/finish_page.dart, lib/presentation/pages/reservation/reservation_page.dart, lib/presentation/pages/signup/signup_page.dart, lib/presentation/pages/signup/tos_page.dart, lib/presentation/widgets/header/login_header.dart, lib/presentation/widgets/header/sign_header.dart
header 수정
header router 수정
header router 꼬임 방지
login과 sign page 전용 header 생성
=>  header 수정

lib/presentation/pages/onboarding/onboarding_page.dart
온보딩 페이지 반응형 수정
온보딩 페이지 반응형으로 수정
온보딩 페이지 반응형
=> 온보딩 페이지 수정

lib/presentation/pages/onboarding/onboarding_page.dart, lib/presentation/pages/profile/profile_page.dart, lib/presentation/pages/reservation/reservation_page.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
예약 페이지 박스 크기 수정
예약 페이지 박스 크기 수정
예약 페이지 박스 크기 수정
reservation_page 의 reseravtion box 크기 수정
=> 예약 페이지 박스 크기 수정

lib/presentation/pages/onboarding/onboarding_page.dart, lib/presentation/pages/profile/profile_page.dart, lib/presentation/pages/reservation/reservation_page.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
모달 글자 크기  및 패딩 수정
모달 글자 크기  및 패딩 수정
모달 글자 크기  및 패딩 수정
=> feat : 스타일 수정

lib/presentation/widgets/box/reservation_cancel_box.dart
예약 취소 완료 비교 수정 완료
현재 날짜와 예약 날짜를 비교하여 cancel값에 따라 예약 취소 예약 완료 여부를 확인
reservation_cancel_box.dart에 checkDate라는 함수 생성
=> 예약 취소 완료 비교 수정 완료

lib/data/models/reservation_model.dart, lib/data/models/reservation_state_model.dart, lib/data/providers/network/apis/reservation/reservation_post_api.dart, lib/presentation/pages/alarm/reservation_page.dart, lib/presentation/pages/reservation/reservation_backup.dart, lib/presentation/pages/reservation/reservation_page.dart, lib/presentation/widgets/box/machine_box.dart, lib/presentation/widgets/box/reservation/reservation_machinebox.dart, lib/presentation/widgets/box/reservation/reservation_weekbox.dart, lib/presentation/widgets/box/reservation_cancel_box.dart
예약 페이지 api 연결 완료
예약 페이지 api 연결
예약 페이지 퍼블리싱
예약 목록 수정
유저 모델 수정
예약 get 모델 수정
예약 페이지 수정
=> 예약 페이지 api 연결 완료

lib/presentation/pages/alarm/alarm_page.dart, lib/presentation/widgets/box/home_notice_box.dart, lib/presentation/widgets/box/reservation/reservation_cancel_box.dart
예약 취소 당일 가능
예약 취소 당일 가능
예약 취소 당일 가능
=> 예약 취소 당일 가능

lib/presentation/pages/login/login_page.dart, lib/presentation/widgets/box/home_activate.dart, lib/presentation/widgets/box/home_notice_box.dart, lib/presentation/widgets/header/main_header.dart, lib/presentation/widgets/modal/userfull_modal.dart
fix : font 수정
fix : font 수정
fix : font 수정
=> fix : font 수정

lib/presentation/pages/reservation/reservation_page.dart
예약 페이지 패딩 수정
예약 페이지 패딩 수정
예약 페이지 패딩 수정
112 에서 88로 수정
=> 예약 페이지 패딩 수정

lib/presentation/pages/alarm/alarm_page.dart, lib/presentation/pages/alarm/notice_page.dart, lib/presentation/pages/alarm/reservation_page.dart, lib/presentation/widgets/box/machine_box.dart, lib/presentation/widgets/button/alarm_button.dart
Alram_page 수정
Alram_page 수정
Alram_page 수정
Alram_button 패딩 수정
=> Alram_page 수정

ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json, ios/Runner/Info.plist, ios/Runner/RunnerDebug.entitlements, ios/Runner/RunnerProfile.entitlements, ios/Runner/RunnerRelease.entitlements, lib/presentation/pages/reservation/reservation_page.dart, lib/presentation/widgets/box/machine_box.dart
예약페이지 세탁실 사진 삽입
예약페이지 세탁실 사진 삽입
예약페이지 세탁실 사진 삽입
=> 예약페이지 세탁실 사진 삽입

lib/presentation/pages/home/home_page.dart, lib/presentation/pages/reservation/reservation_page.dart, lib/presentation/widgets/box/machine_box.dart
홈 회면 반응형 수정
홈 회면 반응형 수정
홈 회면 반응형 수정
=> 홈 회면 반응형 수정
